finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('vids/', views.vids_index, name='index'),
    path('vids/<int:vid_id>/', views.vids_detail, name='detail'),
    path('vids/create/', views.VidCreate.as_view(), name='vids_create'),
    path('vids/<int:pk>/update/', views.VidUpdate.as_view(), name='vids_update'),
    path('vids/<int:pk>/delete/', views.VidDelete.as_view(), name='vids_delete'),
    path('vids/<int:vid_id>/add_progress/', views.add_progress, name='add_progress'),
    path('vids/<int:vid_id>/assoc_character/<int:character_id>/', views.assoc_character, name='assoc_character'),
    path('vids/<int:cat_id>/unassoc_character/<int:character_id>/', views.unassoc_character, name='unassoc_character'),
    # path('toys/', views.ToyList.as_view(), name='toys_index'),
    # path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    # path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

PROGRESS = (
    ('S', 'Started'),
    ('I', 'In-progress'),
    ('C', 'Completed')
)
# Create your models here.

class Character(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

class Vid(models.Model):
    name = models.CharField(max_length=100)
    console = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    release = models.IntegerField()
    characters = models.ManyToManyField(Character)

    #  new code below
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'vid_id': self.id})

class Progress(models.Model):
    date = models.DateField('Progress date')
    progress = models.CharField(
        max_length=1,
        choices=PROGRESS,
        default=PROGRESS[0][0]
    )
    vid = models.ForeignKey(Vid, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_progress_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
# forms.py

from django.forms import ModelForm
from .models import Progress

class ProgressForm(ModelForm):
  class Meta:
    model = Progress
    fields = ['date', 'progress']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import ProgressForm
from .models import Vid, Character
from django.urls import reverse_lazy



from .models import Vid

# Create your views here.
# Define the home view
def home(request):
  # Include an .html file extension - unlike when rendering EJS templates
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def vids_index(request):
  vids = Vid.objects.all()
  return render(request, 'vids/index.html', { 'vids': vids })

def vids_detail(request, vid_id):
  vid = Vid.objects.get(id=vid_id)
  id_list = vid.characters.all().values_list('id')
  characters_vid_doesnt_have = Character.objects.exclude(id__in=id_list)
  progress_form = ProgressForm()
  return render(request, 'vids/detail.html', { 'vid': vid, 'progress_form': progress_form, 'characters': characters_vid_doesnt_have 
  })

class VidCreate(CreateView):
  model = Vid
  fields = ['name', 'console', 'genre', 'release']

class VidUpdate(UpdateView):
  model = Vid
  fields = ['console', 'genre', 'release']

class VidDelete(DeleteView):
  model = Vid
  success_url = '/vids'

def add_progress(request, vid_id):
    form = ProgressForm(request.POST)
    if form.is_valid():
      new_progress = form.save(commit=False)
      new_progress.vid_id = vid_id
      new_progress.save()
    return redirect('detail', vid_id=vid_id)


class CharacterList(ListView):
  model = Character

class CharacterDetail(DetailView):
  model = Character

class CharacterCreate(CreateView):
  model = Character
  fields = ['name', 'color']

  def get_success_url(self):
        return reverse_lazy('characters_list')

class CharacterUpdate(UpdateView):
  model = Character
  fields = ['name', 'color']

class ToyDelete(DeleteView):
  model = Character
  success_url = '/characters'

def assoc_character(request, vid_id, character_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Vid.objects.get(id=vid_id).characters.add(character_id)
  return redirect('detail', vid_id=vid_id)

def unassoc_character(request, vid_id, character_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Vid.objects.get(id=vid_id).characters.add(character_id)
  return redirect('detail', vid_id=vid_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Gaming Guru</h1>
<hr />
<p>Hire the Gaming Guru</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Gaming Guru</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo"
                >&nbsp;&nbsp;Gaming Guru</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li></li>
            <li><a href="{% url 'vids_create' %}">Add a Video Game</a></li>
            <li><a href="{% url 'index' %}">View All Ganes</a></li>
          </ul>
        </div>
        <script>
          const dateEl = document.getElementById("id_date");
          M.Datepicker.init(dateEl, {
            format: "yyyy-mm-dd",
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true,
          });

          const selectEl = document.getElementById("id_progress");
          M.FormSelect.init(selectEl);
        </script>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; Gaming Guru 2023 &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Toy</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'characters_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/character_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Character Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ character.name }}</span>
        <p>Color: {{ character.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'characters_update' character.id %}">Edit</a>
        <a href="{% url 'characters_delete' character.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Character</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/character_list.html
{% extends 'base.html' %} {% block content %}

<h1>Character List</h1>

{% for character in toy_list %}
<a href="{% url 'characters_detail' character.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ character.name }}</span>
      <p>Color: {{ character.color }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/main_app/vid_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Video Game</h1>

<h4>
  Are you sure you want to delete
  <span class="red-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' vid.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/vid_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Video Game</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/vids/detail.html
{% extends 'base.html' %} {% block content %}

<h1>{{ vid.name }} Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title"
          ><span class="blue-text">{{ vid.name }}</span></span
        >
        <p>Console: {{ vid.console }}</p>
        <p>Genre: {{ vid.genre }}</p>
        <p>Year Released: {{ vid.release }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'vids_update' vid.id %}">Edit</a>
        <a href="{% url 'vids_delete' vid.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_progress' vid.id %}" method="POST">
      {% csrf_token %} {{ progress_form.as_p }}
      <input type="submit" class="btn" value="Add Progress" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Progress</th>
        </tr>
      </thead>
      <tbody>
        {% for progress in vid.progress_set.all %}
        <tr>
          <td>{{progress.date}}</td>
          <td>{{progress.get_progress_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ vid.name }}'s Characters</h3>
    {% if vid.characters.count %} {% for vid in vid.characters.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span style="color: {{ vid.color }}">{{ vid.color }} <span style="color: {{ character.color }}"
            >{{ character.color }}</span
          >
          {{ character.name }}
        </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Characters Yet</h5>
    {% endif %}
  </div>

  <div class="col s6">
    <h3>Available Characters</h3>
    {% if characters.count %} {% for character in characters.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <span style="color: {{ character.color }}"
            >{{ character.color }}</span
          >
          {{ character.name }}
        </span>
      </div>
      <div class="card-action">
        <form
          action="{% url 'assoc_character' vid.id character.id %}"
          method="POST"
        >
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{vid.name}} Already Has All Characters Available</h5>
    {% endif %}
  </div>

  <script>
    const dateEl = document.getElementById("id_date");
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });

    const selectEl = document.getElementById("id_progress");
    M.FormSelect.init(selectEl);
  </script>
  {% endblock %}
</div>

main_app/templates/vids/index.html
{% extends 'base.html' %} {% block content %}

<h1>Guru's List</h1>

{% for vid in vids %}
<div class="card">
  <a href="{% url 'detail' vid.id %}">
    <div class="card-content">
      <span class="card-title">{{ vid.name }}</span>
      <p>Console: {{ vid.console }}</p>
      <p>Genre: {{ vid.genre }}</p>
      <p>Year Released: {{ vid.release }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}